new Crawler({
  appId: '',
  apiKey: '',
  rateLimit: 8,
  startUrls: [
    'http://docs.hazzardweb.com/imagepicker/master/',
    'http://docs.hazzardweb.com/',
    'http://docs.hazzardweb.com/imagepicker/2.0/',
    'http://docs.hazzardweb.com/imagepicker/1.4/',
    'http://docs.hazzardweb.com/imagepicker/1.3/',
    'http://docs.hazzardweb.com/imagepicker/1.2/',
    'http://docs.hazzardweb.com/imagepicker/1.1/',
    'http://docs.hazzardweb.com/imagepicker/1.0/',
    'http://docs.hazzardweb.com/filepicker/master/',
    'http://docs.hazzardweb.com/filepicker/2.0/',
    'http://docs.hazzardweb.com/filepicker/1.4/',
    'http://docs.hazzardweb.com/filepicker/1.3/',
    'http://docs.hazzardweb.com/filepicker/1.2/',
    'http://docs.hazzardweb.com/filepicker/1.1/',
    'http://docs.hazzardweb.com/filepicker/1.0/',
    'http://docs.hazzardweb.com/easylogin-pro/master/',
    'http://docs.hazzardweb.com/easylogin-pro/2.0/',
    'http://docs.hazzardweb.com/easylogin-pro/1.4/',
    'http://docs.hazzardweb.com/easylogin-pro/1.3/',
    'http://docs.hazzardweb.com/easylogin-pro/1.2/',
    'http://docs.hazzardweb.com/easylogin-pro/1.1/',
    'http://docs.hazzardweb.com/easylogin-pro/1.0/',
    'http://docs.hazzardweb.com/imageselect/master/',
    'http://docs.hazzardweb.com/imageselect/2.0/',
    'http://docs.hazzardweb.com/imageselect/1.4/',
    'http://docs.hazzardweb.com/imageselect/1.3/',
    'http://docs.hazzardweb.com/imageselect/1.2/',
    'http://docs.hazzardweb.com/imageselect/1.1/',
    'http://docs.hazzardweb.com/imageselect/1.0/',
    'http://docs.hazzardweb.com/ajax-comment-system/master/',
    'http://docs.hazzardweb.com/ajax-comment-system/2.0/',
    'http://docs.hazzardweb.com/ajax-comment-system/1.4/',
    'http://docs.hazzardweb.com/ajax-comment-system/1.3/',
    'http://docs.hazzardweb.com/ajax-comment-system/1.2/',
    'http://docs.hazzardweb.com/ajax-comment-system/1.1/',
    'http://docs.hazzardweb.com/ajax-comment-system/1.0/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/master/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/2.0/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/1.4/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/1.3/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/1.2/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/1.1/',
    'http://docs.hazzardweb.com/ajax-comment-system-laravel/1.0/',
  ],
  renderJavaScript: true,
  sitemaps: [],
  exclusionPatterns: [],
  ignoreCanonicalTo: false,
  discoveryPatterns: ['http://docs.hazzardweb.com/**'],
  schedule: 'at 10:00 on Wednesday',
  actions: [
    {
      indexName: 'hazzardweb',
      pathsToMatch: ['http://docs.hazzardweb.com/**'],
      recordExtractor: ({ $, helpers, url }) => {
        // This could be done by adding a `meta` tag on the website with the `project` and `version`.
        // Read more here: https://docsearch.algolia.com/docs/required-configuration/#introduce-global-information-as-meta-tags
        const pathParts = url.pathname.split('/');
        const project = pathParts[1];
        const version = pathParts[2];

        return helpers.docsearch({
          recordProps: {
            lvl1: '.docs-content h1',
            content: '.docs-content p',
            lvl0: {
              selectors: '',
            },
            lvl2: '.docs-content h2',
            lvl3: '.docs-content h3',
            lvl4: '.docs-content h4',
            lvl5: '.docs-content h5',
            version: {
              defaultValue: [version],
            },
            project: {
              defaultValue: [project],
            },
          },
          indexHeadings: { from: 1, to: 6 },
        });
      },
    },
  ],
  initialIndexSettings: {
    hazzardweb: {
      attributesForFaceting: ['type', 'lang', 'project', 'version'],
      attributesToRetrieve: ['hierarchy', 'content', 'anchor', 'url'],
      attributesToHighlight: ['hierarchy', 'hierarchy_camel', 'content'],
      attributesToSnippet: ['content:10'],
      camelCaseAttributes: ['hierarchy', 'hierarchy_radio', 'content'],
      searchableAttributes: [
        'unordered(hierarchy_radio_camel.lvl0)',
        'unordered(hierarchy_radio.lvl0)',
        'unordered(hierarchy_radio_camel.lvl1)',
        'unordered(hierarchy_radio.lvl1)',
        'unordered(hierarchy_radio_camel.lvl2)',
        'unordered(hierarchy_radio.lvl2)',
        'unordered(hierarchy_radio_camel.lvl3)',
        'unordered(hierarchy_radio.lvl3)',
        'unordered(hierarchy_radio_camel.lvl4)',
        'unordered(hierarchy_radio.lvl4)',
        'unordered(hierarchy_radio_camel.lvl5)',
        'unordered(hierarchy_radio.lvl5)',
        'unordered(hierarchy_radio_camel.lvl6)',
        'unordered(hierarchy_radio.lvl6)',
        'unordered(hierarchy_camel.lvl0)',
        'unordered(hierarchy.lvl0)',
        'unordered(hierarchy_camel.lvl1)',
        'unordered(hierarchy.lvl1)',
        'unordered(hierarchy_camel.lvl2)',
        'unordered(hierarchy.lvl2)',
        'unordered(hierarchy_camel.lvl3)',
        'unordered(hierarchy.lvl3)',
        'unordered(hierarchy_camel.lvl4)',
        'unordered(hierarchy.lvl4)',
        'unordered(hierarchy_camel.lvl5)',
        'unordered(hierarchy.lvl5)',
        'unordered(hierarchy_camel.lvl6)',
        'unordered(hierarchy.lvl6)',
        'content',
      ],
      distinct: true,
      attributeForDistinct: 'url',
      customRanking: [
        'desc(weight.pageRank)',
        'desc(weight.level)',
        'asc(weight.position)',
      ],
      ranking: [
        'words',
        'filters',
        'typo',
        'attribute',
        'proximity',
        'exact',
        'custom',
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: '</span>',
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: 'allOptional',
    },
  },
});
