new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: ["https://roadmap.sh/guides/", "https://roadmap.sh/"],
  renderJavaScript: false,
  sitemaps: [],
  exclusionPatterns: [],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://roadmap.sh/**"],
  schedule: "at 10:30 on Friday",
  actions: [
    {
      indexName: "roadmap",
      pathsToMatch: ["https://roadmap.sh/guides/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "[class*='GuideBodyWrap-'] h2",
            content:
              "[class*='GuideBodyWrap-'] p, [class*='GuideBodyWrap-'] li, p[class*='GuideSubtitle-']",
            lvl0: {
              selectors: "h1[class*='Title-']",
              defaultValue: "Documentation",
            },
            lvl2: "[class*='GuideBodyWrap-'] h3",
            lvl3: "[class*='GuideBodyWrap-'] h4",
            lvl4: "[class*='GuideBodyWrap-'] h5",
            lvl5: "[class*='GuideBodyWrap-'] h6",
            tags: {
              defaultValue: ["guides"],
            },
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "roadmap",
      pathsToMatch: [
        "https://roadmap.sh**/**",
        "!https://roadmap.sh/guides/**",
      ],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "[class*='Summary-'] h1",
            content:
              "[class*='Summary-'] p, [class*='Summary-'] li, p[class*='Description-']",
            lvl0: {
              selectors: "h1[class*='Title-']",
              defaultValue: "Documentation",
            },
            lvl2: "[class*='Summary-'] h2",
            lvl3: "[class*='Summary-'] h3",
            lvl4: "[class*='Summary-'] h4",
            lvl5: "[class*='Summary-'] h5",
            lvl6: "[class*='Summary-'] h6",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    roadmap: {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.page_rank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});