new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: ["https://iterm2.com/documentation", "https://iterm2.com/"],
  renderJavaScript: false,
  sitemaps: [],
  exclusionPatterns: [
    "**/utilities/**",
    "**/_**",
    "**/_**/**",
    "**/3**",
    "**/3**/**",
    "**/2**",
    "**/2**/**",
    "**/**downloads**",
    "**/**downloads**/**",
  ],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://iterm2.com/**"],
  schedule: "at 15:40 on Wednesday",
  actions: [
    {
      indexName: "iterm2",
      pathsToMatch: ["https://iterm2.com/documentation**/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".doc-section h1",
            content:
              ".doc-section p, .doc-section li, .doc-section td:last-child",
            lvl0: {
              selectors: "nav .active",
              defaultValue: "Documentation",
            },
            lvl2: ".doc-section h3",
            lvl3: ".doc-section h4",
            lvl4: ".doc-section h5, .doc-section td:first-child",
            lvl5: ".doc-section h6",
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "iterm2",
      pathsToMatch: [
        "https://iterm2.com/**",
        "!https://iterm2.com/documentation**/**",
      ],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".main h3",
            content: ".main p, .main li",
            lvl0: {
              selectors: "nav .active",
              defaultValue: "Documentation",
            },
            lvl2: ".main h4",
            lvl3: ".main h5",
            lvl4: ".main h6",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    iterm2: {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});