new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://embark.status.im/docs/",
    "https://embark.status.im/",
    "https://embark.status.im/tutorials/",
    "https://embark.status.im/plugins/",
  ],
  renderJavaScript: false,
  sitemaps: ["https://embark.status.im/sitemap.xml"],
  exclusionPatterns: [],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://embark.status.im/**"],
  schedule: "at 20:20 on Tuesday",
  actions: [
    {
      indexName: "embark",
      pathsToMatch: ["https://embark.status.im/docs/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".o-standard-page h1",
            content: ".o-standard-page p, .o-standard-page li",
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: ".o-standard-page h2",
            lvl3: ".o-standard-page h3",
            lvl4: ".o-standard-page h4",
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "embark",
      pathsToMatch: ["https://embark.status.im/tutorials/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".o-standard-page h1",
            content: ".o-standard-page p, .o-standard-page li",
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: ".o-standard-page h2",
            lvl3: ".o-standard-page h3",
            lvl4: ".o-standard-page h4",
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "embark",
      pathsToMatch: ["https://embark.status.im/plugins/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: ".o-standard-page h1",
            content: ".o-standard-page p, .o-standard-page li",
            lvl0: {
              selectors: "",
              defaultValue: "Documentation",
            },
            lvl2: ".o-standard-page h2",
            lvl3: ".o-standard-page h3",
            lvl4: ".o-standard-page h4",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    embark: {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});