new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://ai2thor.allenai.org/ithor/documentation/",
    "https://ai2thor.allenai.org/",
    "https://ai2thor.allenai.org/robothor/documentation/",
  ],
  renderJavaScript: false,
  sitemaps: ["https://ai2thor.allenai.org/sitemap.xml"],
  exclusionPatterns: [],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://ai2thor.allenai.org/**"],
  schedule: "at 01:20 on Tuesday",
  actions: [
    {
      indexName: "allenai",
      pathsToMatch: ["https://ai2thor.allenai.org/ithor/documentation/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "[class*='MainContent'] h2",
            content: "[class*='MainContent'] p, [class*='MainContent'] li",
            lvl0: {
              selectors: "[class*='MainContent'] h1",
            },
            lvl2: "[class*='MainContent'] h3",
            lvl3: "[class*='MainContent'] h4",
            lvl4: "[class*='MainContent'] h5",
            lvl5: "[class*='MainContent'] h6",
            project: {
              defaultValue: ["ithor"],
            },
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "allenai",
      pathsToMatch: ["https://ai2thor.allenai.org/robothor/documentation/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "[class*='MainContent'] h2",
            content: "[class*='MainContent'] p, [class*='MainContent'] li",
            lvl0: {
              selectors: "[class*='MainContent'] h1",
            },
            lvl2: "[class*='MainContent'] h3",
            lvl3: "[class*='MainContent'] h4",
            lvl4: "[class*='MainContent'] h5",
            lvl5: "[class*='MainContent'] h6",
            project: {
              defaultValue: ["robothor"],
            },
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    allenai: {
      attributesForFaceting: ["type", "lang", "project"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});