new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://docs.axelor.com/adk/",
    "https://docs.axelor.com/",
    "https://docs.axelor.com/abs/",
  ],
  renderJavaScript: false,
  sitemaps: ["http://docs.axelor.com/sitemap.xml"],
  exclusionPatterns: ["**/javadoc/**", "**/latest/**"],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://docs.axelor.com/**"],
  schedule: "at 01:50 on Tuesday",
  actions: [
    {
      indexName: "axelor",
      pathsToMatch: ["https://docs.axelor.com/adk/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "article.doc h1",
            content: "article.doc p, article.doc li",
            lvl0: {
              selectors: "nav > ul > li:nth-child(2) > a",
              defaultValue: "Documentation",
            },
            lvl2: "article.doc h2",
            lvl3: "article.doc h3",
            lvl4: "article.doc h4",
            lvl5: "article.doc h5",
            tags: {
              defaultValue: ["adk"],
            },
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "axelor",
      pathsToMatch: ["https://docs.axelor.com/abs/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "article.doc h1",
            content: "article.doc p, article.doc li",
            lvl0: {
              selectors: "nav > ul > li:nth-child(2) > a",
              defaultValue: "Documentation",
            },
            lvl2: "article.doc h2",
            lvl3: "article.doc h3",
            lvl4: "article.doc h4",
            lvl5: "article.doc h5",
            tags: {
              defaultValue: ["abs"],
            },
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    axelor: {
      attributesForFaceting: ["type", "lang", "version", "tags"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});