new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://www.selenium.dev/documentation/",
    "https://www.selenium.dev/",
    "https://selenium.dev/documentation/",
    "https://selenium.dev/",
    "https://selenium.dev/documentation/de/getting_started/quick/",
    "https://selenium.dev/documentation/en/getting_started/quick/",
    "https://selenium.dev/documentation/es/getting_started/quick/",
    "https://selenium.dev/documentation/nl/getting_started/quick/",
    "https://selenium.dev/documentation/zh-cn/getting_started/quick/",
    "https://selenium.dev/documentation/fr/getting_started/quick/",
    "https://selenium.dev/documentation/ja/getting_started/quick/",
    "https://selenium.dev/documentation/ko/getting_started/quick/",
  ],
  renderJavaScript: false,
  sitemaps: ["https://www.selenium.dev/sitemap.xml"],
  exclusionPatterns: [],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://www.selenium.dev/**", "https://selenium.dev/**"],
  schedule: "at 15:00 on Friday",
  actions: [
    {
      indexName: "selenium",
      pathsToMatch: ["https://www.selenium.dev/documentation/**"],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "#body-inner h2",
            content: "#body-inner p, #body-inner li",
            lvl0: {
              selectors: "#body-inner h1",
            },
            lvl2: "#body-inner h3",
            lvl3: "#body-inner h4",
            lvl4: "#body-inner h5",
            lvl5: "#body-inner h6",
            lang: "",
          },
          indexHeadings: true,
        });
      },
    },
    {
      indexName: "selenium",
      pathsToMatch: [
        "https://selenium.dev/documentation/**",
        "https://selenium.dev/documentation/de/getting_started/quick/**",
        "https://selenium.dev/documentation/en/getting_started/quick/**",
        "https://selenium.dev/documentation/es/getting_started/quick/**",
        "https://selenium.dev/documentation/nl/getting_started/quick/**",
        "https://selenium.dev/documentation/zh-cn/getting_started/quick/**",
        "https://selenium.dev/documentation/fr/getting_started/quick/**",
        "https://selenium.dev/documentation/ja/getting_started/quick/**",
        "https://selenium.dev/documentation/ko/getting_started/quick/**",
      ],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "#body-inner h2",
            content: "#body-inner p, #body-inner li",
            lvl0: {
              selectors: "#body-inner h1",
            },
            lvl2: "#body-inner h3",
            lvl3: "#body-inner h4",
            lvl4: "#body-inner h5",
            lvl5: "#body-inner h6",
            lang: "",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    selenium: {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.page_rank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
      separatorsToIndex: "_",
    },
  },
});