new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: ["https://docs.stackery.io/"],
  renderJavaScript: false,
  sitemaps: ["https://docs.stackery.io/sitemap.xml"],
  exclusionPatterns: [
    "https://docs.stackery.io/docs/next**",
    "https://docs.stackery.io/docs/next**/**",
    "https://docs.stackery.io/docs/4.1.0**",
    "https://docs.stackery.io/docs/4.1.0**/**",
    "https://docs.stackery.io/docs/4.0.2**",
    "https://docs.stackery.io/docs/4.0.2**/**",
    "https://docs.stackery.io/docs/4.0.1**",
    "https://docs.stackery.io/docs/4.0.1**/**",
    "https://docs.stackery.io/docs/4.0.0**",
    "https://docs.stackery.io/docs/4.0.0**/**",
    "https://docs.stackery.io/docs/3.13.4**",
    "https://docs.stackery.io/docs/3.13.4**/**",
    "https://docs.stackery.io/docs/3.12.2**",
    "https://docs.stackery.io/docs/3.12.2**/**",
    "https://docs.stackery.io/docs/3.12.0**",
    "https://docs.stackery.io/docs/3.12.0**/**",
    "https://docs.stackery.io/docs/3.11.8**",
    "https://docs.stackery.io/docs/3.11.8**/**",
    "https://docs.stackery.io/docs/3.11.7**",
    "https://docs.stackery.io/docs/3.11.7**/**",
    "https://docs.stackery.io/docs/3.11.5**",
    "https://docs.stackery.io/docs/3.11.5**/**",
    "https://docs.stackery.io/docs/3.11.4**",
    "https://docs.stackery.io/docs/3.11.4**/**",
    "https://docs.stackery.io/docs/3.11.2**",
    "https://docs.stackery.io/docs/3.11.2**/**",
    "https://docs.stackery.io/docs/3.11.1**",
    "https://docs.stackery.io/docs/3.11.1**/**",
    "https://docs.stackery.io/docs/3.11.0**",
    "https://docs.stackery.io/docs/3.11.0**/**",
    "https://docs.stackery.io/docs/3.10.0**",
    "https://docs.stackery.io/docs/3.10.0**/**",
    "https://docs.stackery.io/docs/3.9.7**",
    "https://docs.stackery.io/docs/3.9.7**/**",
    "https://docs.stackery.io/docs/3.9.2**",
    "https://docs.stackery.io/docs/3.9.2**/**",
    "https://docs.stackery.io/docs/3.9.1**",
    "https://docs.stackery.io/docs/3.9.1**/**",
    "https://docs.stackery.io/docs/3.9.0**",
    "https://docs.stackery.io/docs/3.9.0**/**",
    "https://docs.stackery.io/docs/3.8.0**",
    "https://docs.stackery.io/docs/3.8.0**/**",
    "https://docs.stackery.io/docs/3.7.7**",
    "https://docs.stackery.io/docs/3.7.7**/**",
    "https://docs.stackery.io/docs/3.7.6**",
    "https://docs.stackery.io/docs/3.7.6**/**",
    "https://docs.stackery.io/docs/3.7.5**",
    "https://docs.stackery.io/docs/3.7.5**/**",
    "https://docs.stackery.io/docs/3.7.4**",
    "https://docs.stackery.io/docs/3.7.4**/**",
    "https://docs.stackery.io/docs/3.7.1**",
    "https://docs.stackery.io/docs/3.7.1**/**",
    "https://docs.stackery.io/docs/3.7.0**",
    "https://docs.stackery.io/docs/3.7.0**/**",
    "https://docs.stackery.io/docs/3.6.0**",
    "https://docs.stackery.io/docs/3.6.0**/**",
    "https://docs.stackery.io/docs/3.5.3**",
    "https://docs.stackery.io/docs/3.5.3**/**",
    "https://docs.stackery.io/docs/3.5.1**",
    "https://docs.stackery.io/docs/3.5.1**/**",
    "https://docs.stackery.io/docs/3.5.0**",
    "https://docs.stackery.io/docs/3.5.0**/**",
    "https://docs.stackery.io/docs/3.4.3**",
    "https://docs.stackery.io/docs/3.4.3**/**",
    "https://docs.stackery.io/docs/3.4.1**",
    "https://docs.stackery.io/docs/3.4.1**/**",
    "https://docs.stackery.io/docs/3.4.0**",
    "https://docs.stackery.io/docs/3.4.0**/**",
    "https://docs.stackery.io/docs/3.3.0**",
    "https://docs.stackery.io/docs/3.3.0**/**",
    "https://docs.stackery.io/docs/3.2.2**",
    "https://docs.stackery.io/docs/3.2.2**/**",
    "https://docs.stackery.io/docs/3.2.1**",
    "https://docs.stackery.io/docs/3.2.1**/**",
    "https://docs.stackery.io/docs/3.1.1**",
    "https://docs.stackery.io/docs/3.1.1**/**",
    "https://docs.stackery.io/docs/3.1.0**",
    "https://docs.stackery.io/docs/3.1.0**/**",
    "https://docs.stackery.io/docs/3.0.0**",
    "https://docs.stackery.io/docs/3.0.0**/**",
    "https://docs.stackery.io/docs/2.13.0**",
    "https://docs.stackery.io/docs/2.13.0**/**",
    "https://docs.stackery.io/docs/2.12.0**",
    "https://docs.stackery.io/docs/2.12.0**/**",
    "https://docs.stackery.io/docs/2.11.0**",
    "https://docs.stackery.io/docs/2.11.0**/**",
    "https://docs.stackery.io/docs/2.10.0**",
    "https://docs.stackery.io/docs/2.10.0**/**",
    "https://docs.stackery.io/docs/2.9.0**",
    "https://docs.stackery.io/docs/2.9.0**/**",
    "https://docs.stackery.io/docs/2.8.1**",
    "https://docs.stackery.io/docs/2.8.1**/**",
    "https://docs.stackery.io/docs/2.8.0**",
    "https://docs.stackery.io/docs/2.8.0**/**",
    "https://docs.stackery.io/docs/2.7.2**",
    "https://docs.stackery.io/docs/2.7.2**/**",
    "https://docs.stackery.io/docs/2.6.0**",
    "https://docs.stackery.io/docs/2.6.0**/**",
    "https://docs.stackery.io/docs/2.5.2**",
    "https://docs.stackery.io/docs/2.5.2**/**",
    "https://docs.stackery.io/docs/2.5.1**",
    "https://docs.stackery.io/docs/2.5.1**/**",
    "https://docs.stackery.io/docs/2.5.0**",
    "https://docs.stackery.io/docs/2.5.0**/**",
    "https://docs.stackery.io/docs/2.4.1**",
    "https://docs.stackery.io/docs/2.4.1**/**",
    "https://docs.stackery.io/docs/2.4.0**",
    "https://docs.stackery.io/docs/2.4.0**/**",
    "https://docs.stackery.io/docs/2.3.0**",
    "https://docs.stackery.io/docs/2.3.0**/**",
    "https://docs.stackery.io/docs/2.2.1**",
    "https://docs.stackery.io/docs/2.2.1**/**",
    "https://docs.stackery.io/docs/2.2.0**",
    "https://docs.stackery.io/docs/2.2.0**/**",
    "https://docs.stackery.io/docs/2.1.1**",
    "https://docs.stackery.io/docs/2.1.1**/**",
    "https://docs.stackery.io/docs/2.1.0**",
    "https://docs.stackery.io/docs/2.1.0**/**",
    "https://docs.stackery.io/docs/2.0.0**",
    "https://docs.stackery.io/docs/2.0.0**/**",
    "https://docs.stackery.io/docs/1.5.8**",
    "https://docs.stackery.io/docs/1.5.8**/**",
    "https://docs.stackery.io/docs/1.5.7**",
    "https://docs.stackery.io/docs/1.5.7**/**",
    "https://docs.stackery.io/docs/1.5.5**",
    "https://docs.stackery.io/docs/1.5.5**/**",
    "https://docs.stackery.io/docs/1.5.4**",
    "https://docs.stackery.io/docs/1.5.4**/**",
    "https://docs.stackery.io/docs/1.5.3**",
    "https://docs.stackery.io/docs/1.5.3**/**",
    "https://docs.stackery.io/docs/1.5.2**",
    "https://docs.stackery.io/docs/1.5.2**/**",
    "https://docs.stackery.io/docs/1.5.1**",
    "https://docs.stackery.io/docs/1.5.1**/**",
    "https://docs.stackery.io/docs/1.5.0**",
    "https://docs.stackery.io/docs/1.5.0**/**",
    "https://docs.stackery.io/docs/1.4.7**",
    "https://docs.stackery.io/docs/1.4.7**/**",
    "https://docs.stackery.io/docs/1.4.6**",
    "https://docs.stackery.io/docs/1.4.6**/**",
    "https://docs.stackery.io/docs/1.4.5**",
    "https://docs.stackery.io/docs/1.4.5**/**",
    "https://docs.stackery.io/docs/1.4.3**",
    "https://docs.stackery.io/docs/1.4.3**/**",
    "https://docs.stackery.io/docs/1.3.0**",
    "https://docs.stackery.io/docs/1.3.0**/**",
    "https://docs.stackery.io/docs/0.1.0**",
    "https://docs.stackery.io/docs/0.1.0**/**",
    "https://docs.stackery.io/docs/0.0.5**",
    "https://docs.stackery.io/docs/0.0.5**/**",
    "https://docs.stackery.io/docs/0.0.4**",
    "https://docs.stackery.io/docs/0.0.4**/**",
    "https://docs.stackery.io/docs/0.0.3**",
    "https://docs.stackery.io/docs/0.0.3**/**",
    "https://docs.stackery.io/docs/0.0.2**",
    "https://docs.stackery.io/docs/0.0.2**/**",
    "https://docs.stackery.io/docs/0.0.1**",
    "https://docs.stackery.io/docs/0.0.1**/**",
  ],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://docs.stackery.io/**"],
  schedule: "at 15:40 on Friday",
  actions: [
    {
      indexName: "stackery",
      pathsToMatch: ["https://docs.stackery.io**/**"],
      recordExtractor: ({ $, helpers }) => {
        // Removing DOM elements we don't want to crawl
        const toRemove = ".hash-link";
        $(toRemove).remove();

        return helpers.docsearch({
          recordProps: {
            lvl1: ".post h1",
            content: ".post article p, .post article li",
            lvl0: {
              selectors: ".navGroup > h3.collapsible",
              defaultValue: "Documentation",
            },
            lvl2: ".post h2",
            lvl3: ".post h3",
            lvl4: ".post h4",
          },
          indexHeadings: false,
        });
      },
    },
  ],
  initialIndexSettings: {
    stackery: {
      attributesForFaceting: ["type", "lang", "language", "version"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});