new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://www.loginradius.com/docs/api?accesscode=RaQaDLUY",
    "https://www.loginradius.com/",
    "https://www.loginradius.com/docs/",
  ],
  renderJavaScript: true,
  sitemaps: ["https://www.loginradius.com/docs/sitemap.xml"],
  exclusionPatterns: [
    "https://www.loginradius.com/docs/api/v1/**",
    "https://www.loginradius.com/docs/getting-started/glossary**",
    "https://www.loginradius.com/docs/getting-started/glossary**/**",
    "https://www.loginradius.com/docs/api/changelog**",
    "https://www.loginradius.com/docs/api/changelog**/**",
    "**/**?action**",
    "**/**?action**/**",
    "**/**return_url**",
    "**/**return_url**/**",
  ],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://www.loginradius.com/**"],
  schedule: "at 05:30 on Thursday",
  actions: [
    {
      indexName: "loginradius",
      pathsToMatch: [
        "https://www.loginradius.com/docs/**",
        "https://www.loginradius.com/docs/api?accesscode=RaQaDLUY**/**",
      ],
      recordExtractor: ({ $, helpers }) => {
        return helpers.docsearch({
          recordProps: {
            lvl1: "#content h2, #mdcontainer h1",
            content: "#content p, #content li, #mdcontainer p, #mdcontainer li",
            lvl0: {
              selectors: "#content h1, ul label.md-nav__link--active",
              defaultValue: "Documentation",
            },
            lvl2: "#content h3, .docs-header h3, #mdcontainer h2",
            lvl3: "#content h4, #mdcontainer h3",
            lvl4: "#content h5, #mdcontainer h4",
          },
          indexHeadings: { from: 1, to: 6 },
        });
      },
    },
  ],
  initialIndexSettings: {
    loginradius: {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});