new Crawler({
  appId: "",
  apiKey: "",
  rateLimit: 8,
  startUrls: [
    "https://felgo.com/doc/",
    "https://felgo.com/",
    "https://felgo.com/doc/vplayapps-appbutton/",
  ],
  renderJavaScript: false,
  sitemaps: [],
  exclusionPatterns: [
    "**/**?utm**",
    "**/**?utm**/**",
    "**/felgo.com/doc/qt/qsggeometrynode/qsgsimpletexturenode/qsgsimplerectnode**",
    "**/felgo.com/doc/qt/qsggeometrynode/qsgsimpletexturenode/qsgsimplerectnode**/**",
    "**/**(/([a-z][A-Z])*\\/){6}**",
    "**/**(/([a-z][A-Z])*\\/){6}**/**",
    "**/**([a-z-][a-z-]*)/(?=\\1+)**",
    "**/**([a-z-][a-z-]*)/(?=\\1+)**/**",
  ],
  ignoreCanonicalTo: false,
  discoveryPatterns: ["https://felgo.com/**"],
  schedule: "at 04:40 on Saturday",
  actions: [
    {
      indexName: "v-play",
      pathsToMatch: [
        "https://felgo.com/doc/**",
        "https://felgo.com/doc/vplayapps-appbutton/**",
      ],
      recordExtractor: ({ $, helpers }) => {
        // Removing DOM elements we don't want to crawl
        const toRemove = ".toc, .breadcrumb";
        $(toRemove).remove();

        return helpers.docsearch({
          recordProps: {
            lvl1: ".doc-page h2",
            content: ".doc-page p, .doc-page li",
            lvl0: {
              selectors: ".doc-page h1",
            },
            lvl2: ".doc-page h3",
            lvl3: ".doc-page h4",
            lvl4: ".doc-page h5",
          },
          indexHeadings: true,
        });
      },
    },
  ],
  initialIndexSettings: {
    "v-play": {
      attributesForFaceting: ["type", "lang"],
      attributesToRetrieve: ["hierarchy", "content", "anchor", "url"],
      attributesToHighlight: ["hierarchy", "hierarchy_camel", "content"],
      attributesToSnippet: ["content:10"],
      camelCaseAttributes: ["hierarchy", "hierarchy_radio", "content"],
      searchableAttributes: [
        "unordered(hierarchy_radio_camel.lvl0)",
        "unordered(hierarchy_radio.lvl0)",
        "unordered(hierarchy_radio_camel.lvl1)",
        "unordered(hierarchy_radio.lvl1)",
        "unordered(hierarchy_radio_camel.lvl2)",
        "unordered(hierarchy_radio.lvl2)",
        "unordered(hierarchy_radio_camel.lvl3)",
        "unordered(hierarchy_radio.lvl3)",
        "unordered(hierarchy_radio_camel.lvl4)",
        "unordered(hierarchy_radio.lvl4)",
        "unordered(hierarchy_radio_camel.lvl5)",
        "unordered(hierarchy_radio.lvl5)",
        "unordered(hierarchy_radio_camel.lvl6)",
        "unordered(hierarchy_radio.lvl6)",
        "unordered(hierarchy_camel.lvl0)",
        "unordered(hierarchy.lvl0)",
        "unordered(hierarchy_camel.lvl1)",
        "unordered(hierarchy.lvl1)",
        "unordered(hierarchy_camel.lvl2)",
        "unordered(hierarchy.lvl2)",
        "unordered(hierarchy_camel.lvl3)",
        "unordered(hierarchy.lvl3)",
        "unordered(hierarchy_camel.lvl4)",
        "unordered(hierarchy.lvl4)",
        "unordered(hierarchy_camel.lvl5)",
        "unordered(hierarchy.lvl5)",
        "unordered(hierarchy_camel.lvl6)",
        "unordered(hierarchy.lvl6)",
        "content",
      ],
      distinct: true,
      attributeForDistinct: "url",
      customRanking: [
        "desc(weight.pageRank)",
        "desc(weight.level)",
        "asc(weight.position)",
      ],
      ranking: [
        "words",
        "filters",
        "typo",
        "attribute",
        "proximity",
        "exact",
        "custom",
      ],
      highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
      highlightPostTag: "</span>",
      minWordSizefor1Typo: 3,
      minWordSizefor2Typos: 7,
      allowTyposOnNumericTokens: false,
      minProximity: 1,
      ignorePlurals: true,
      advancedSyntax: true,
      attributeCriteriaComputedByMinProximity: true,
      removeWordsIfNoResults: "allOptional",
    },
  },
});
